# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
stages:
  - test
  - mirror

test_docs:
  stage: test
  image: europeanxfel/karabo-ci:miniconda-3-006
  script:
    - pip install -r source/requirements.txt
    - make doctest
  only:
    refs:
      - merge_requests

include:
  - project: karabo/gitlabci
    file: .mirror-device.yml
    ref: main

