# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.

stages:
  - test
  - mirror

test_docs:
  stage: test
  image: europeanxfel/karabo-ci:miniconda-3-006
  script:
    - pip install -r source/requirements.txt
    - make doctest
  only:
    refs:
      - merge_requests


internal_mirror_publish:
  stage: mirror
  image: europeanxfel/karabo-ci:miniconda-3-006
  before_script:
    - echo "Approved?"
    - echo $CI_MERGE_REQUEST_APPROVED
    - echo "And approved end"
    - echo "And branch name"
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo "And branch name end"
  only:
    refs:
      - merge_requests
  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.xfel.eu/Karabo/contriboptouts.git
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.xfel.eu/karaboDevices/HowToMiddlelayer.git --branch main --single-branch HowToMiddlelayerMain
    - cd HowToMiddlelayerMain
    - git remote rm origin
    - git remote add internal_mirror https://oauth2:$HTM_MIRROR_TOKEN@git.xfel.eu/karaboDevices/HowToMiddlelayerMirror.git
    - git push --mirror internal_mirror
    - cd ..
    - rm -rf HowToMiddlelayerMain
    - git clone https://oauth2:$HTM_MIRROR_TOKEN@git.xfel.eu/karaboDevices/HowToMiddlelayerMirror.git
    - cd HowToMiddlelayerMirror
    - git-filter-repo --strip-blobs-bigger-than 100M
    - git-filter-repo --mailmap ../contriboptouts/karabo-mailmap
    - git remote add internal_mirror https://oauth2:$HTM_MIRROR_TOKEN@git.xfel.eu/karaboDevices/HowToMiddlelayerMirror.git
    - git push -u internal_mirror main --force --prune
    - git push internal_mirror --tags --force
